local editor = require('kz.editor')
editor.space(2)

vim.opt_local.suffixesadd:append('.js')
vim.opt_local.suffixesadd:append('.json')
vim.opt_local.suffixesadd:append('.jsx')
vim.opt_local.suffixesadd:append('.vue')
vim.opt_local.suffixesadd:append('.svelte')
vim.opt_local.suffixesadd:append('index.js')
vim.opt_local.suffixesadd:append('index.jsx')
