vim.lsp.enable('basedpyright')
vim.lsp.enable('bashls')
vim.lsp.enable('circleci_ls')
vim.lsp.enable('gopls')
vim.lsp.enable('helm_ls')
vim.lsp.enable('jsonls')
vim.lsp.enable('lua_ls')
vim.lsp.enable('terraformls')
vim.lsp.enable('tilt_ls')
vim.lsp.enable('tsgo')
-- vim.lsp.enable('vtsls')
vim.lsp.enable('yamlls')
vim.lsp.enable('zk')

vim.api.nvim_create_user_command('LspHealth', function()
  vim.cmd('checkhealth vim.lsp')
end, {})
