#!/bin/sh
#
# A hook script to prepare the commit log message. It will try to add the
# relevant commit log into the commit template as a comment for reference.

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

case "$COMMIT_SOURCE,$SHA1" in
 ,|template,|commit,HEAD)
   temp_file=$(mktemp)
   cleanup() {
     rm -f "$temp_file"
   }

   trap cleanup EXIT

   COMMIT_LOG=$(git new | sed 's/^/# /')

   awk \
     'BEGIN {s=ARGV[1]; ARGV[1]=""} /^#/ && !inserted { printf "%s\n#\n",s; inserted=1 } 1' \
     "$COMMIT_LOG" \
     "$COMMIT_MSG_FILE" > "$temp_file" && mv "$temp_file" "$COMMIT_MSG_FILE" ;;
 *) ;;
esac
