# ============================================================================
# macOS config
# ============================================================================

# Pipe copied text to system clipboard
set-option          -s  copy-command       "pbcopy"

# vim: ft=tmux
