---
projects:
  max_depth: 4
  root: ~/Projects
  # Cache remote projects for 1 day
  ttl: 86400
  remote_patterns:
    - zkhvan/* -> ./personal/
    - gptzero/*

    - cli/cli -> ./oss/
    - junegunn/fzf -> ./oss/
    - zk-org/zk -> ./oss/
    - terraform-aws-modules/* -> ./oss/
    - circleci-public/* -> ./oss/
